#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp $TMPDIR/resource-request.XXXXXX)
cat > $payload <&0

#xcode_api_url=$(jq -r '.source.xcode_api_url // ""' < $payload)

curl http://uklonjenkd01.zipcar.com:8080/job/Zipcar%20Android/api/json > builds.txt
build_number=$(cat builds.txt | jq '.["builds"][0]["number"]')

echo '[{ "ref": "'$build_number'" }]' >&3
