#!/bin/bash
# vim: set ft=sh

set -e
set -x

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

cd $1

payload=$(mktemp $TMPDIR/resource-request.XXXXXX)
cat > $payload <&0
cat $payload

#xcode_api_url=$(jq -r '.source.xcode_api_url // ""' < $payload)

curl http://uklonjenkd01.zipcar.com:8080/job/Zipcar%20Android/api/json > builds.txt
ls -lh builds.txt

build_number=$(cat builds.txt | jq '.["builds"][0]["number"]')
echo $build_number

build_url=$(cat builds.txt | jq -r '.["builds"][0]["url"]')
echo $build_url

jq -n '{
  "version": { "ref": "'$build_number'" },
  "metadata": [
    { "name": "commit", "value": "'$build_number'" },
    { "name": "author", "value": "'$build_url'" }
  ]
}' >&3