#!/bin/bash
# vim: set ft=sh

set -e
set -x

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

cd $1

payload=$(mktemp $TMPDIR/resource-request.XXXXXX)
cat > $payload <&0
cat $payload

jenkins_url=$(jq -r '.source.jenkins_url // ""' < $payload)
job_name=$(jq -r '.source.job_name // ""' < $payload)
job_path=$(jq -r '.source.job_path // ""' < $payload)
builds_file=$(jq -r '.source.builds_file // ""' < $payload)

full_jenkins_url=$jenkins_url$job_name$job_path
curl $full_jenkins_url > $builds_file
ls -lh $builds_file

build_number=$(cat $builds_file | jq '.["builds"][0]["number"]')
echo $build_number

build_url=$(cat $builds_file | jq -r '.["builds"][0]["url"]')
echo $build_url

jq -n '{
  "version": { "ref": "'$build_number'" },
  "metadata": [
    { "name": "commit", "value": "'$build_number'" },
    { "name": "author", "value": "'$build_url'" }
  ]
}' >&3